name: SolanaDevMinecraftAstraL
version: 1.0
main: com.SolanaDevMinecraft.App
api-version: 1.19
author: Amauri
description: Plugin que permite ver token Solana Dev no Minecraft
commands:
  saldo:
    description: Verifica o saldo bancário.
    usage: /saldo
  loan:
    description: Solicita um empréstimo. pega emprestimo com 13 do L
    usage: /loan <quantidade>
  paydebt:
    description: Paga parte ou toda a dívida.
    usage: /paydebt <quantidade>
  invest:
    description: Realiza um investimento.
    usage: /invest <quantidade>
  solbalance:
    description: Verifica o saldo da carteira Solana.
    usage: /solbalance
  soltransfer:
    description: Transfere SOL para outro jogador.
    usage: /soltransfer <quantidade> <jogador_destino>
  buycurrency:
    description: Compra moedas do jogo usando Solana.
    usage: /buycurrency <quantidade_SOL>
  createwallet:
    description: Cria uma carteira Solana para o jogador.
    usage: /createwallet
  buyapple:
    description: Compra uma Maçã Encantada.
    usage: /buyapple
  buyemerald:
    description: Compra uma Esmeralda.
    usage: /buyemerald
  buydiamond:
    description: Compra um Diamante.
    usage: /buydiamond
  buygold:
    description: Compra uma Barra de Ouro.
    usage: /buygold
  buyiron:
    description: Compra uma Barra de Ferro.
    usage: /buyiron
  buynetherite:
    description: Compra uma Barra de Netherite.
    usage: /buynetherite
  buySpinningWand:
    description: Compra uma Varinha Giratória.
    usage: /buySpinningWand
  buyLapis:
    description: Compra um Lápis Lazúli.
    usage: /buyLapis
  buyQuartz:
    description: Compra um Quartzo.
    usage: /buyQuartz
  buyRedstone:
    description: Compra uma Redstone.
    usage: /buyRedstone
  buyClay:
    description: Compra um Bloco de Argila.
    usage: /buyClay
  buySandBlock:
    description: Compra um Bloco de Areia.
    usage: /buySandBlock
  buyAllTools:
    description: Compra todas as Ferramentas.
    usage: /buyAllTools
  buyAllFood:
    description: Compra toda a Comida.
    usage: /buyAllFood
  buySimpleBook:
    description: Compra um Livro Simples.
    usage: /buySimpleBook
  buyEmeraldBlock:
    description: Compra um Bloco de Esmeralda.
    usage: /buyEmeraldBlock
  buySimpleMap:
    description: Compra um Mapa Simples.
    usage: /buySimpleMap
  buySimpleCompass:
    description: Compra uma Bússola Simples.
    usage: /buySimpleCompass
  buySimpleFishingRod:
    description: Compra uma Vara de Pesca Simples.
    usage: /buySimpleFishingRod
  buyAxolotlBucket:
    description: Balde com peixe Simples.
    usage: /buyAxolotlBucket
  transferirtokengamer:
    description: Transfere moeda do banco para o jogador.
    usage: /transferirtokengamer <quantidade>
  
  
  
